### ISSUE TITLE
翻译任务认领说明

### ISSUE THREAD

**Issue by QC-L** [docschina/Recoil#61]
> 注意：一次尽量只认领一篇，给其他小伙伴留些机会~

开始翻译前，请务必阅读[翻译流程](https://github.com/docschina/Recoil/issues/62)

从 Todo List 中选取未被人领取过的文章：

未被领取过：

* [ ] installation

领取过：

* [ ] installation (@QC-L)

领取过，已完成：

* [x] installation (@QC-L) #1

**领取方式，在本 issues 下评论即可。**

认领任务格式：

```markdown
Section | Title | 译者 | 完成时间
-- | -- | -- | --
introduction |  installation | @QC-L | 2021.02.03 - 2021.02.04
```

示例效果：

Section | Title | 译者 | 完成时间
-- | -- | -- | --
introduction |  installation | @QC-L | 2021.02.03 - 2021.02.04

## 任务认领列表

Todo List:

- [x] [introduction](https://github.com/docschina/Recoil/tree/docs/docs/docs/introduction)
  - [x] [core-concepts](https://github.com/docschina/Recoil/tree/docs/docs/docs/introduction/core-concepts.md)
  - [x] [getting-started](https://github.com/docschina/Recoil/tree/docs/docs/docs/introduction/getting-started.mdx)
  - [x] [installation](https://github.com/docschina/Recoil/tree/docs/docs/docs/introduction/installation.md)
  - [x] [motivation](https://github.com/docschina/Recoil/tree/docs/docs/docs/introduction/motivation.md)
- [x] [basic-tutorial](https://github.com/docschina/Recoil/tree/docs/docs/docs/basic-tutorial)
  - [x] [selectors](https://github.com/docschina/Recoil/tree/docs/docs/docs/basic-tutorial/selectors.md)
  - [x] [intro](https://github.com/docschina/Recoil/tree/docs/docs/docs/basic-tutorial/intro.md)
  - [x] [atoms](https://github.com/docschina/Recoil/tree/docs/docs/docs/basic-tutorial/atoms.mdx)
- [x] [api-reference](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference)
  - [x] [core](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core)
    - [x] [useRecoilBridgeAcrossReactRoots](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useRecoilBridgeAcrossReactRoots.md) (@QC-L) #70 
    - [x] [atom](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/atom.md)
    - [x] [isRecoilValue](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/isRecoilValue.md)
    - [x] [Loadable](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/Loadable.md) (@KimYangOfCat) #67 
    - [x] [RecoilRoot](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/RecoilRoot.md)
    - [x] [selector](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/selector.md) (@KnowsCount) #65 
    - [x] [Snapshot](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/Snapshot.md) (@KnowsCount) #87
    - [x] [useGetRecoilValueInfo](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useGetRecoilValueInfo.md) (@KimYangOfCat) #68 
    - [x] [useGotoRecoilSnapshot](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useGotoRecoilSnapshot.md) (@KimYangOfCat) #66 
    - [x] [useRecoilCallback](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useRecoilCallback.md)  (@KnowsCount)
    - [x] [useRecoilSnapshot](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useRecoilSnapshot.md) (@KimYangOfCat) #81 
    - [x] [useRecoilState](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useRecoilState.md)
    - [x] [useRecoilStateLoadable](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useRecoilStateLoadable.md) (@KnowsCount) #78
    - [x] [useRecoilTransactionObserver](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useRecoilTransactionObserver.md) (@KimYangOfCat) #71 
    - [x] [useRecoilValue](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useRecoilValue.md)
    - [x] [useRecoilValueLoadable](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useRecoilValueLoadable.md) (@Ivocin) #85 
    - [x] [useResetRecoilState](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useResetRecoilState.md)
    - [x] [useSetRecoilState](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useSetRecoilState.md)
  - [x] [utils](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils)
    - [x] [waitForNone](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils/waitForNone.md) (@KimYangOfCat) #82 
    - [x] [atomFamily](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils/atomFamily.md) (@KnowsCount)
    - [x] [constSelector](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils/constSelector.md) (@KnowsCount) #77
    - [x] [errorSelector](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils/errorSelector.md) (@KimYangOfCat) #72 
    - [x] [noWait](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils/noWait.md) (@KimYangOfCat) #83 
    - [x] [selectorFamily](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils/selectorFamily.md) (@KimYangOfCat) #84 
    - [x] [waitForAll](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils/waitForAll.md) (@KimYangOfCat) #75 
    - [x] [waitForAllSettled](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils/waitForAllSettled.md) (@KimYangOfCat) #74 
    - [x] [waitForAny](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils/waitForAny.md) (@KimYangOfCat) #73 
- [x] [guides](https://github.com/docschina/Recoil/tree/docs/docs/docs/guides)
  - [x] [asynchronous-data-queries](https://github.com/docschina/Recoil/tree/docs/docs/docs/guides/asynchronous-data-queries.md) (@KimYangOfCat ) #95 
  - [x] [atom-effects](https://github.com/docschina/Recoil/tree/docs/docs/docs/guides/atom-effects.md) (@KnowsCount) #92
  - [x] [dev-tools](https://github.com/docschina/Recoil/tree/docs/docs/docs/guides/dev-tools.md) (@wjq990112) #80 
  - [x] [testing](https://github.com/docschina/Recoil/tree/docs/docs/docs/guides/testing.md) (@KimYangOfCat) #69 
- [ ] [blog](https://github.com/docschina/Recoil/tree/docs/docs/blog)
  - [ ] [2020-05-30-0.0.8-released](https://github.com/docschina/Recoil/tree/docs/docs/blog/2020-05-30-0.0.8-released.md)
  - [ ] [2020-06-18-0.0.10-released](https://github.com/docschina/Recoil/tree/docs/docs/blog/2020-06-18-0.0.10-released.md)
  - [ ] [2020-09-15-0.0.11-released](https://github.com/docschina/Recoil/tree/docs/docs/blog/2020-09-15-0.0.11-released.mdx)
  - [ ] [2020-10-30-0.1.1-released](https://github.com/docschina/Recoil/tree/docs/docs/blog/2020-10-30-0.1.1-released.md) (@KnowsCount)
  - [x] [2021-03-22-0.2.0-released](https://github.com/docschina/Recoil/tree/docs/docs/blog/2021-03-22-0.2.0-released.md) (@KnowsCount) #94
  - [x] [2021-05-14-0.3.0-released.md](https://github.com/docschina/Recoil/blob/docs/docs/blog/2021-05-14-0.3.0-released.md) (@KnowsCount) #93

**Comment by QC-L** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/core |  useRecoilBridgeAcrossReactRoots | @QC-L | 2021.05.07 - 2021.05.10

**Comment by c-z-chen** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/core |  selector | @KnowsCount | 2021.05.07 - 2021.05.08

**Comment by Ivocin** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/core |  useRecoilValueLoadable | @Ivocin  | 2021.05.07 - 2021.05.13

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/core |  useGotoRecoilSnapshot | @KimYangOfCat | 2021.05.07 - 2021.05.08

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/core |   Loadable | @KimYangOfCat | 2021.05.08 - 2021.05.08

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/core |   useGetRecoilValueInfo | @KimYangOfCat | 2021.05.08 - 2021.05.08

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/core |  useRecoilTransactionObserver | @KimYangOfCat | 2021.05.08 - 2021.05.08

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guides |  testing | @KimYangOfCat | 2021.05.08 - 2021.05.08

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/utils |  errorSelector | @KimYangOfCat | 2021.05.08 - 2021.05.08

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/utils |  waitForAny  | @KimYangOfCat | 2021.05.08 - 2021.05.08

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/utils | waitForAllSettled  | @KimYangOfCat | 2021.05.08 - 2021.05.08

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/utils | waitForAll  | @KimYangOfCat | 2021.05.08 - 2021.05.08

**Comment by c-z-chen** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/core |  useRecoilStateLoadable | @KnowsCount | 2021.05.08 - 2021.05.09

**Comment by c-z-chen** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/utils | constSelector | @KnowsCount | 2021.05.08 - 2021.05.09

**Comment by wjq990112** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guides/dev-tools |  Development Tools | @wjq990112  | 2021.05.10 - 2021.05.15

**Comment by c-z-chen** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/core |  useRecoilCallback | @KnowsCount | 2021.05.11 - 2021.05.13

**Comment by c-z-chen** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/core |  Snapshot | @KnowsCount | 2021.05.11 - 2021.05.13

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/utils | useRecoilSnapshot | @KimYangOfCat | 2021.05.11 - 2021.05.12

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/utils | waitForNone | @KimYangOfCat | 2021.05.11 - 2021.05.12

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/utils | noWait | @KimYangOfCat | 2021.05.11 - 2021.05.12

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/utils | selectorFamily | @KimYangOfCat | 2021.05.12 - 2021.05.14

**Comment by c-z-chen** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api-reference/utils | atomFamily | @KnowsCount | 2021.05.15 - 2021.05.16

**Comment by QC-L** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guides | asynchronous-data-queries | @QC-L| 2021.05.20 - 2021.05.22

**Comment by c-z-chen** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guides | atom-effects | @KnowsCount | 2021.05.20 - 2021.05.25

**Comment by c-z-chen** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
blog | 2021-03-22-0.2.0-released | @KnowsCount | 2021.05.22 - 2021.05.25

**Comment by c-z-chen** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
blog | 2021-05-14-0.3.0-released.md | @KnowsCount | 2021.05.23 - 2021.05.26

**Comment by c-z-chen** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
blog | 2020-10-30-0.1.1-released | @KnowsCount | 2021.05.28 - 2021.05.30
